export const SET_BUSINESS_INFORMATION = 'SET_BUSINESS_INFORMATION';
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const SET_AUTO_APPLY_GRANTS = 'SET_AUTO_APPLY_GRANTS';
export const SET_GRANTS_LIST = 'SET_GRANTS_LIST';
export const SET_APPLICATIONS_LIST = 'SET_APPLICATIONS_LIST';
export const SET_USER_SIGNUP = 'SET_USER_SIGNUP';
// src/redux/actionTypes.js

